### ISSUE TITLE
Add an example sushiswap pair call

### ISSUE THREAD

**Issue by wildmolasses** [sunday-club/learning-uniswap#10]
In the same way that we did a simple call on a uniswap pair, let's do it for sushiswap.

If you have any questions, this issue is a good place to ask by leaving comments.

**Comment by Scapestudio** [comment]
Ok @wildmolasses great. in the meantime that @kupcha is reviewing and approving the changes that we did on sunday, I can ask a few questions. The main one is, and I think I know the answer but I just wanna be sure, we used this address: "0x0d4a11d5eeaac28ec3f61d100daf4d40471f1852" which is the UniswapV2Pair contract address of the WETH and USDT pair. So now this one "0x06da0fd433C1A5d7a4faa01111c044910A184553" it should be the one for the sushiswap exchanges, and this contract has the same function ``` getReserves()``` of the uniswap contract. Am I right? 
I'm gonna attach the etherscan link of the sushiswap pair contract so you can see it also https://etherscan.io/address/0x06da0fd433c1a5d7a4faa01111c044910a184553#readContract

**Comment by Scapestudio** [comment]
If all of the above is correct this is the sudo code:
```js
ethers.provider.on("block", async () => {
  const pairAddrSushiSwap = "0x06da0fd433C1A5d7a4faa01111c044910A184553";
  const pairSushiSwap = await ethers.getContractAt(["function getReserves() view returns (uint112, uint112, uint32)"], 
  pairAddrSushiSwap);
  const reservesSushiSwap = await pairSushiSwap.getReserves();
  console.log(`${reservesSushiSwap[0].toSring()} ---- ${reservesSushiSwap[1].toString()}`);
});
```

Also can you remind me how to run the code in vs code

**Comment by wildmolasses** [comment]
> So now this one "0x06da0fd433C1A5d7a4faa01111c044910A184553" it should be the one for the sushiswap exchanges, and this contract has the same function getReserves() of the uniswap contract. Am I right?

Yes, this is the pair contract for WETH<>USDT on sushiswap. It has the same `getReserves` function, because sushiswap and uniswap use the same pair contracts. Sushiswap is a uniswap fork! (interesting?)

> If all of the above is correct this is the sudo code

Looks good

> Also can you remind me how to run the code in vs code

I will create an issue to solve this
