### ISSUE TITLE
What data do we need to query each block?

### ISSUE THREAD

**Issue by kupcha** [sunday-club/learning-uniswap#11]
So we decided we will run a check each block... what exactly do we want to see? I will try to put together a list of things we would like to see, how we will get that information, and begin to define a struct we can return on each block to aid our bot's decision making.

**Comment by Scapestudio** [comment]
Hi @kupcha believe that we want to see if on each block there is an arbitrage opportunity between the two exchanges (uniswap and sushiswap). If there is we should sell or buy on one exchange and sell to the other.

**Comment by wildmolasses** [comment]
> Hi @kupcha believe that we want to see if on each block there is an arbitrage opportunity between the two exchanges (uniswap and sushiswap). If there is we should sell or buy on one exchange and sell to the other.

@Scapestudio that is correct. we will need to go into more detail, though. what does it mean to "see if there is an arbitrage opportunity?" What pieces of data do we need to pull to calculate this? And then what kind of logic do we need to use to do the calculation? These are the things that we should explore in this issue that @kupcha is working on.

**Comment by kupcha** [comment]
## We will evaluate if an arbitrage opportunity exists each block
```js
ethers.provider.on("block", async () => {
      const tradeData = getTradeData();
      // where evaluation dictates whether an arbitrage occurs
      const evaluation = evaluateTradeData(tradeData);
      
      if (evaluation < 0){ /** buy on sushi then sell on uniswap */ }
      else if (evaluation > 0){ /** buy on uniswap then sell on sushi */ }
      else { /** nothing happens */ } 
});
```

## What data do we need to properly assess for profitability?
```js
const tradeData = {
     currentBlock : Block,
     uniswapRate : Price,
     sushiswapRate : Price,
     gasEstimate : BigNumber
}
```
Is there anything else that would be helpful here?



## How would we like to evaluate price?

There are multiple ways offered by Uniswap to get price. @wildmolasses please let me know if I am misrepresenting anything in this section or if you have anything additional to add.

### 1. **Pair** data

```js
getOutputAmount(inputAmount: TokenAmount): [TokenAmount, Pair]
```

Pricing function for exact input amounts. Returns maximum output amount based on current reserves and the new Pair that would exist if the trade were executed.

So theoretically we could define our token pair, a designated amount to buy with, and then call this function on both uniswap and sushiswap and determine if a big enough difference exists.  

### 2. **Route** data
```js
     const USDT = new Token(
       ChainId.MAINNET,
       "0xdac17f958d2ee523a2206206994597c13d831ec7",
       6
     );


     const pair = await Fetcher.fetchPairData(USDT, WETH[USDT.chainId]);
     const route = new Route([pair], USDT); 
     // here we are passing USDT as the input token so the transaction would be USDT --> WETH
     // const route = new Route([pair], WETH[USDT.chainId]); would be the alternative

     const uniswapMidPrice = route.midPrice.toSignificant(6);
     const midPriceInverted = route.midPrice.invert().toSignificant(6);
```

My gut is telling me Route Mid Price would be optimal way to do this but I would like to understand this more.


## How do we estimate cost of transcation?

I found two potential options.

1. 

```js
  ethers.provider.getGasPrice() ⇒ Promise< BigNumber >
```

2. 

```js
ethers.provider.estimateGas( transaction ) ⇒ Promise< BigNumber >
```

Option 2 requires a transaction to be passed. So we define our swap and pass to this function to get a gas estimate? If that is possible I would think this way is ideal as I imagine defining specifics of transaction would give a more precise estimate.


### Next Steps

- Determine if these are the best practices for fetching the data we are after
- Once the above is identified we can better define the getTradeData() and evaluateTradeData()
- Define a threshold that needs to exist to trigger an arbitrage
