### ISSUE TITLE
Create new script in package.json that runs our index file

### ISSUE THREAD

**Issue by wildmolasses** [sunday-club/learning-uniswap#12]
From #10 we wanted to know how to run our script.

Create a new script entry inside package.json called "start"

start should be set to `"hardhat run ./src/index.ts"`

after we can try running it with `yarn start --network mainnet`

add instructions on how to use to README.md

**Comment by wildmolasses** [comment]
Either @Scapestudio or @kupcha can work on this; just assign yourself, then branch from main, make your commit, and push to this remote repo and then make a pull request. let me know if you need help with that workflow and i can write more instructions.

**Comment by Scapestudio** [comment]
Hi @wildmolasses, I can try to work on this task. For the workflow I'll pull the updated repository with ```git pull```, then Ill branch from main with ```git checkout -b [updating.jsonFile]```, than I'll make the commit and push to the remote repo with ```git push origin [updating.jsonFile]```. If all I've said it's fine my only concern is the pull request. I just go here and say pull request, and than create a pull request selecting the updating.jsonFile branch right?

**Comment by Scapestudio** [comment]
Oh it looks like @kupcha is working on it

**Comment by kupcha** [comment]
I had just assigned this to myself but hadn't done anything for it if it's something you'd like to do @Scapestudio . I'll continue with my other stuff for now and get to it if you don't.

**Comment by Scapestudio** [comment]
Ok lets see what @wildmolasses says about the workflow and if I start working on it I'll let you know

**Comment by wildmolasses** [comment]
Looks good. I would suggest using dashes in the branch name, maybe call it
"add-start-script"

**Comment by Scapestudio** [comment]
Ok thank you @wildmolasses. @kupcha I'll try to work on this task, I'll assign myself too. @wildmolasses should I add the sushiswap code too this "add-start-script" branch?

**Comment by Scapestudio** [comment]
@wildmolasses, I'm able to add all the necessary new script to the .json file and to the sushiswap code to the index.ts. The only problem that I encounter is that when I create the branch after ```git checkout -b "add-start-script"```, and than ```git push origin "add-start-script"```, I go to the github repository page, click on pull request, create pull request and click on the "add-start-script" branch and it says that the two branches main and the add-start-script are identical?? I don't know why because on vscode it does show the changes that I've made.... Waiting for tips

**Comment by kupcha** [comment]
Could it be the changes you made on the "add-start-script" branch weren't committed?

**Comment by wildmolasses** [comment]
>  @wildmolasses should I add the sushiswap code too this "add-start-script" branch?

No, these are two separate issues, so we would like to see 2 separate PRs for the changes!

**Comment by Scapestudio** [comment]
Ok @wildmolasses. @kupcha and @wildmolasses, I thought that if I commit everything that I have add would go in to the main branch... Should I commit after the ```git checkout -b "add-start-script"``` command and before the ```push origin "add-start-script"```?

**Comment by wildmolasses** [comment]
yes @Scapestudio I recommend reviewing a git tutorial (https://www.atlassian.com/git/tutorials/saving-changes)

Just like before you cook, you need to get the ingredients onto the table, it's the same thing -- before you commit, you need to add the changed files to the stage.

Trying to use multiple branches is difficult at first, but this is stuff that is absolutely needed for collaborative coding!
https://www.atlassian.com/git/tutorials/using-branches
